project:
  type: website
  render:
    - "*.qmd"
    - "!slides/" # don't knit slides when website is updated
    - "!files/"
  resources:
    - "files/"
    - "slides/"
    - "images/"

website:
  title: "ECON 480 — Econometrics"
  favicon: "files/images/metrics_hex.png"
  open-graph: true
  twitter-card: true
  image: "files/images/metrics_hex.png"
  navbar:
    pinned: true
    search: true
    logo: "files/images/metrics_hex.png"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: Content
        href: content/index.qmd
      - text: Assignments
        href: assignments/index.qmd
      - text: Resources
        href: resources/index.qmd
      - icon: slack
        href: "https://hoodcollegeeconomics.slack.com"
      - icon: cloud-fill
        href: "rstudio.cloud"
  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      contents:
        - section: "Overview"
          contents: 
            - content/index.qmd
        - section: "I. Data Analysis in R"
          contents: 
            - text: "1.1 — Introduction to Econometrics"
              href: content/1.1-content.qmd
            - text: "1.2 — Meet R"
              href: content/1.2-content.qmd
            - text: "1.3 — Data Visualization"
              href: content/1.3-content.qmd
            - text: "1.4 — Data Wrangling"
              href: content/1.4-content.qmd
            - text: "1.5 — Optimize Workflow"
              href: content/1.5-content.qmd
        - section: "II. Linear Regression"
          contents: 
            - text: "2.1 — Data 101 & Descriptive Statistics"
              href: content/2.1-content.qmd
            - text: "2.2 — Random Variables & Distributions"
              href: content/2.2-content.qmd
            - text: "2.3 — Simple Linear Regression"
              href: content/2.3-content.qmd
            - text: "2.4 — Goodness of Fit and Bias"
              href: content/2.4-content.qmd
            - text: "2.5 — Precision and Diagnostics"
              href: content/2.5-content.qmd
            - text: "2.6 — Inference for Regression"
              href: content/2.6-content.qmd
            - text: "2.7 — Hypothesis Testing for Regression"
              href: content/2.7-content.qmd
        - section: "III. Causal Inference"
          contents:
            - text: "3.1 — The Fundamental Problem of Causal Inference"
              href: content/3.1-content.qmd
            - text: "3.2 — DAGs"
              href: content/3.2-content.qmd
            - text: "3.3 — Omitted Variable Bias"
              href: content/3.3-content.qmd
        - section: "IV. Multivariate Regression"
          contents:
            - text: "4.1 — Multivariate OLS Estimators"
              href: content/4.1-content.qmd
            - text: "4.2 — Writing an Empirical Paper"
              href: content/4.2-content.qmd
 
    - title: "R Practice"
      style: "docked"
      search: false
      contents:
        - text: "1.2 — Meet R"
          href: r/1.2-r.qmd
        - text: "1.3 — Data Visualization"
          href: r/1.3-r.qmd
        - text: "1.4 — Data Wrangling"
          href: r/1.4-r.qmd
        - text: "1.5 — Optimize Workflow"
          href: r/1.5-r.qmd
        - text: "2.5 — Precision and Diagnostics"
          href: r/2.5-r.qmd
        - text: "2.7 — Hypothesis Testing for Regression"
          href: r/2.7-r.qmd
        - text: "3.2 — DAGs"
          href: r/3.2-r.qmd
        - text: "4.1 — Multivariate OLS Estimators"
          href: r/4.1-r.qmd
              
    - title: "Assignments"
      style: "docked"
      search: false
      contents:
        - section: "Assignments"
          contents:
            - assignments/index.qmd
        - section: "Problem Sets"
          contents:
            - text: "Instructions"
              href: assignments/problem-sets.qmd
            - text: "Preliminary Survey"
              href: assignments/00-preliminary-survey.qmd
            - text: "Problem Set 1"
              href: assignments/01-problem-set.qmd
            - text: "Problem Set 2"
              href: assignments/02-problem-set.qmd
            - text: "Problem Set 3"
              href: assignments/03-problem-set.qmd
            - text: "Problem Set 4"
              href: assignments/04-problem-set.qmd
        - section: "Exams"
          contents:
            - text: "Midterm Exam"
              href: assignments/01-exam.qmd
        - text: "Research Paper"
          href: assignments/research-paper.qmd
    
    - title: "R Practice"
      style: "docked"
      contents:
        - text: "1.2 — Meet R"
          href: r/1.2-r.qmd
        - text: "1.3 — Data Visualization"
          href: r/1.3-r.qmd
        - text: "1.4 — Data Wrangling"
          href: r/1.4-r.qmd
        - text: "2.5 — Precision and Diagnostics"
          href: r/2.5-r.qmd
        - text: "2.7 — Hypothesis Testing for Regression"
          href: r/2.7-r.qmd
        - text: "3.2 — DAGs"
          href: r/3.2-r.qmd
    
    - title: "Resources"
      style: "docked"
      search: true
      contents:
        - section: "Overview"
          contents:
          - resources/index.qmd
        - section: "Computing Guides"
          contents:
          - href: resources/pdfs.qmd
            text: "How to Make a PDF"
          - href: resources/zipping.qmd
            text: "Zipping and Unzipping Files"
        - section: "R Resources"
          contents:
          - href: resources/installing-r.qmd
            text: "Installing R and R Studio"
          - href: resources/coding-style.qmd
            text: "Suggested Code Style Guide"
        - section: "Advice"
          contents:
          - href: resources/tips.qmd
            text: "Tips for Success"
          - href: resources/data.qmd
            text: "Data Sources & Suggestions"
          - href: resources/appendices.qmd
            text: "Math & R Appendices"
          - href: resources/statistics.qmd
            text: "Statistics Guide"
        - section: "Math & Stats Appendices"
          contents:
          - href: resources/appendices/2.1-appendix.qmd
            text: "Appendix 2.1"
          - href: resources/appendices/2.2-appendix.qmd
            text: "Appendix 2.2"
          - href: resources/appendices/2.3-appendix.qmd
            text: "Appendix 2.3"
          - href: resources/appendices/2.4-appendix.qmd
            text: "Appendix 2.4"
          - href: resources/appendices/2.6-appendix.qmd
            text: "Appendix 2.6"
            
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - cosmo
      - html/custom.scss
    css: styles.css
    toc: true

editor: visual

