---
format:
  revealjs:
    theme: [default, custom.scss]
    logo: "../images/metrics_hex.png"
    footer: "[ECON 480 — Econometrics](https://metricsF22.classes.ryansafner.com)"
    height: 900
    width: 1600
    df-print: paged
    slide-number: c
    chalkboard: true
overview: true
execute:
  echo: false
  warning: false
  freeze: auto
---

##  {data-menu-title="Title Slide" background-image="images/metrics_title_slide.png"}

[Final Review]{.custom-title}

[ECON 480 • Econometrics • Fall 2022]{.custom-subtitle}

[Dr. Ryan Safner <br> Associate Professor of Economics]{.custom-author}

[<a href="mailto:safner@hood.edu"><i class="fa fa-paper-plane fa-fw"></i>safner\@hood.edu</a> <br> <a href="https://github.com/ryansafner/metricsF22"><i class="fa fa-github fa-fw"></i>ryansafner/metricsF22</a><br> <a href="https://metricsF22.classes.ryansafner.com"> <i class="fa fa-globe fa-fw"></i>metricsF22.classes.ryansafner.com</a><br>]{.custom-institution}

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(broom)
library(haven)
library(kableExtra)
library(patchwork)
library(fontawesome)
library(gapminder)
library(ggthemes)
library(scales)
library(infer)
library(modelsummary)
knitr::opts_chunk$set(echo=F,
                      message=F,
                      warning=F)
update_geom_defaults("label", list(family = "Fira Sans Condensed"))
update_geom_defaults("text", list(family = "Fira Sans Condensed"))

```

## Major Models & Extensions

- Causality
  - Fundamental problem of causal inference, potential outcomes
  - DAGs, front-doors/back-doors, controlling

. . .

- Multivariate OLS
  - Omitted Variable Bias
  - Variance/Multicollinearity

## Major Models & Extensions

- Categorical data
  - Interpreting dummies, group means
  - Using categorical variables as dummies
  - dummy variable trap
  - interaction effects

. . .

- Nonlinear Models & Transforming Variables
  - quadratic model
  - higher-order polynomials
  - logs
  - standardizing variables
  - joint hypothesis (F-tests)

## Major Models & Extensions

- Panel data
  - pooled regression & problems
  - fixed effects

- Difference-in-differences

- Instrumental variables
  
## Question 1

What are the two conditions for a variable $Z$ to cause .shout[omitted variable bias] if it is left out of the regression?

## Question 2

$$Wages_i=\beta_0+\beta_1 \, Education_i + \beta_2 \, Age_i + \beta_3 \, Experience_i + u_i$$

Suppose $Education_i$ and $Age_i$ are highly correlated

. . .

- Does this [bias]{.hi-purple} $\hat{\beta_1}$ and $\hat{\beta_2}$?

. . .

- What will happen to the [variance]{.hi-purple} of $\hat{\beta_1}$ and $\hat{\beta_2}$?
  - How can we measure this? 

## Question 3

$$Cholesterol_i=\beta_0+\beta_1 \, Treated_i+u_i$$

- $Treated_i$ is a dummy variable $= \begin{cases} 1 & \text{if person received treatment}\\ 0 & \text{if person did not receive treatment}\\ \end{cases}$

. . .

- What is $\hat{\beta_0}$?

. . .

- What is $\hat{\beta_1}$?

. . .

- What is the average cholesterol level for someone who recieved treatment? 

## Question 4

$$Y_i=\beta_0+\beta_1 \, Red_i+\beta_2 \, Orange_i+\beta_3 \, Yellow_i+\beta_4 \, Green_i+\beta_5 \, Blue_i$$

Suppose the **color** of observation $i$ can be either $\{$Red, Orange, Yellow, Green, Blue, Purple $\}$

. . .

- What is $\hat{\beta_0}$?

. . .

- What is $\hat{\beta_1}$?

. . .

- What is the average value of $Y_i$ for $Green$ observations?

. . .

- Why can't we add $\beta_6 \, Purple_i$?

## Question 5

$$\widehat{Utility}_i=\beta_0+\beta_1 \, Eggs_i+\beta_2 \, Breakfast_i+\beta_3 (Eggs_i \times Breakfast_i)$$

$Breakfast_i$ is a dummy variable $= \begin{cases} 1 & \text{if meal i is breakfast}\\ 0 & \text{if meal i is not breakfast}\\ \end{cases}$

. . .

- What is $\hat{\beta_1}$?

. . .

- What is $\hat{\beta_2}$?

. . .

- What is $\hat{\beta_3}$?

. . .

- We have two regressions (one for Breakfast; one for Not Breakfast)
    - how can we determine if the intercepts are different?
    - how can we determine if the slopes are different?


## Question 6

$$\widehat{Utility}_i=2+4\text{ Ice Cream Cones}_i-1\text{ Ice Cream Cones}_i^2$$

. . .

- What is the marginal effect of eating 1 more Ice Cream Cone?

. . .

- What if we *start* with 1 Ice Cream Cone?

. . .

- What if we *start* with 4 Ice Cream Cones?

. . .

- What amount of ice cream cones will *maximize* utility?

. . .

- How would we know if we should add $\text{Ice Cream Cones}_i^3$?

## Question 7

$$\ln(GDP_i)=10+2\text{ population (in billions)}_i$$

- Interpret $\hat{\beta_1}$ in context.

. . .

$$\ln(GDP_i)=10+0.1 \, \ln(\text{population}_i)$$

- Interpret $\hat{\beta_1}$ in context.

## Question 8

- Explain *what* an $F$-test is used for.

. . .

- Explain *how* an $F$-statistic is estimated (roughly).


## Question 9

Consider a two-way fixed effects model: 

$$\text{Divorce Rate}_{it}=\beta_1 \text{Divorce Law}_{it}+\alpha_i+\theta_t+\epsilon_{it}$$
for State $i$ at time $t$

. . .

- Why do we need $\alpha_i$ and $\theta_t$?

. . .

- What sorts of things are in $\alpha_i$?

. . .

- What sorts of things are in $\theta_t$? 

## Question 10

Suppose Maryland passes a law (and other States do not) that affects crime rates. Consider the following model: 

$$\text{Crime Rate}_{it}=\beta_0+\beta_1 \, \text{Maryland}_{i}+\beta_2 \, \text{After}_t+\beta_3  \, (\text{Maryland}_i \times \text{After}_t)$$
for State $i$ at time $t$

. . .

- What must we assume about Maryland over time?

. . .

- What is the average crime rate for other states before the law?

. . .

- What is the average crime rate for Maryland after the law?

. . .

- What is the *causal effect* of passing the law?

## Question 12

- What are the two conditions required for an instrument to be **valid**?
  - How is this different from the conditions for omitted variable bias?

. . .

- How can we test each condition?

. . .

- How do we run a two-stage least squares regression?